[project]
name = "leisure-teatime"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = [
    "click>=8.1.8",
    "requests>=2.31.0",
    "lxml>=5.3.1",
    "openpyxl>=3.1.3",
    "pandas>=1.1.5",
]
requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
task = {call = "work.tools.task_generator:main"}
exec = {call = "work.tools.task_executor:main"}
