[project]
name = "leisure-teatime"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "D7x7z49", email = "85430783+D7x7z49@users.noreply.github.com"},
]
dependencies = [
    "playwright>=1.35.0",
    "click>=8.1.8",
    "python-dotenv>=0.21.1",
    "prompt-toolkit>=3.0.48",
    "lxml>=5.3.1",
    "ijson>=3.3.0",
    "aiofiles>=23.2.1",
]
requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false


[tool.pdm.scripts]
dev = "python -m core.cli"
